### ISSUE TITLE
Relicense to CC BY 4.0

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxDocs#90]
## Relicensing

The FlaxDocs repository currently is *all rights reserved*.[\[1\]](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) 

This is a problem, and we'd like to ask you for permission to change the license to the very permissive [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/).

Pinging @mafiesto4 @stefnotch @herocrab @W2Wizard @bolognatic @Withaust @MinhCT @jb-perrier @iainmckay @Wolfos @mxruben @honzapatCZ @NordonOscillius @Galbi3000 @mlavik1 @realDLPS @tom-weiland @nothingTVatYT @nove1398 @molodoy-chelovek @brbrmensch @Clawthorn @GoaLitiuM @Evildea @iliyalb @jfaz13 @Muchaszewski , since you contributed to this repository.  Thank you very much for improving the documentation by the way! <3

**If you're fine with changing the license, please respond to this issue.**

## More info, feel free to skip this section
Disclaimer: I'm not a laywer, the following is just my very limited understanding of the rules. Please actually ask a lawyer when you have legal questions.

In most countries (jurisdictions), when you create something, you own it. (copyright)
For anyone else to view it, or to change it, or similar, they have to get your permission. (lots of exceptions)

The reason why things can be put onto GitHub, and why other people can look at it, is because of their Terms of Service. The GitHub ToS basically says "you uploaded public code to GitHub, now GitHub is allowed to display the code".

Most projects actually want people to be able to use their work, to contribute and more. For example, it should be possible to copy-paste a snippet of the documentation and put it into your code. This is why nearly every project has a license. A license is the legal document that actually allows you to do certain things, as long as you follow the rules.

The FlaxDocs repository doesn't have LICENSE file or anything. This means that the default still applies, where everyone owns their contributions. (all rights are reserved). This is not ideal. We'd like to fix that, by changing the license to the very open [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license. That effectively means that
- Anyone will be able to contribute to the documentation, same as before.
- Anyone will be able to use the documentation, cite it, tweak it, as long as they give appropriate credit. *This is an issue at the moment.*

**Comment by stefnotch** [comment]
I'm fine with changing the license :)

**Comment by mafiesto4** [comment]
Fine by me!

**Comment by nothingTVatYT** [comment]
I'm fine with this license change.

Am Mo., 17. Apr. 2023 um 11:38 Uhr schrieb Wojciech Figat <
***@***.***>:

**Comment by jb-perrier** [comment]
Of course it's ok for me !

**Comment by brbrmensch** [comment]
sure

**Comment by Withaust** [comment]
👍

**Comment by Wolfos** [comment]
No problem👍

**Comment by W2Wizard** [comment]
👍 All good!

-------- Original Message --------
Subject: [FlaxEngine/FlaxDocs] Relicense to CC BY 4.0 (Issue #90)
Date: Monday, April 17, 2023 11:36 CEST
From: stefnotch ***@***.***>
Reply-To: FlaxEngine/FlaxDocs ***@***.***>

To: FlaxEngine/FlaxDocs ***@***.***>
CC: W2Wizard ***@***.***>, Mention ***@***.***>


 
 Relicensing
The FlaxDocs repository currently is all rights reserved.[1]
This is a problem, and we'd like to ask you for permission to change the license to the very permissive Creative Commons Attribution 4.0 International.
Pinging @mafiesto4 @stefnotch @herocrab @W2Wizard @bolognatic @Withaust @MinhCT @jb-perrier @iainmckay @Wolfos @mxruben @honzapatCZ @NordonOscillius @Galbi3000 @mlavik1 @realDLPS @tom-weiland @nothingTVatYT @nove1398 @molodoy-chelovek @brbrmensch @Clawthorn @GoaLitiuM @Evildea @iliyalb @jfaz13 @Muchaszewski , since you contributed to this repository. Thank you very much for improving the documentation by the way! <3
If you're fine with changing the license, please respond to this issue.More info, feel free to skip this section
Disclaimer: I'm not a laywer, the following is just my very limited understanding of the rules. Please actually ask a lawyer when you have legal questions.
In most countries (jurisdictions), when you create something, you own it. (copyright)
For anyone else to view it, or to change it, or similar, they have to get your permission. (lots of exceptions)
The reason why things can be put onto GitHub, and why other people can look at it, is because of their Terms of Service. The GitHub ToS basically says "you uploaded public code to GitHub, now GitHub is allowed to display the code".
Most projects actually want people to be able to use their work, to contribute and more. For example, it should be possible to copy-paste a snippet of the documentation and put it into your code. This is why nearly every project has a license. A license is the legal document that actually allows you to do certain things, as long as you follow the rules.
The FlaxDocs repository doesn't have LICENSE file or anything. This means that the default still applies, where everyone owns their contributions. (all rights are reserved). This is not ideal. We'd like to fix that, by changing the license to the very open CC BY 4.0 license. That effectively means that
 * Anyone will be able to contribute to the documentation, same as before. * Anyone will be able to use the documentation, cite it, tweak it, as long as they give appropriate credit. This is an issue at the moment.

**Comment by MinhCT** [comment]
I'm cool! 👍

**Comment by Muchaszewski** [comment]
Sounds great 👍

**Comment by GoaLitiuM** [comment]
Sounds good 👍

**Comment by bolognatic** [comment]
Fine with me.

**Comment by mxruben** [comment]
I'm fine with it

**Comment by mlavik1** [comment]
Sure, sounds like a good idea :)

**Comment by iainmckay** [comment]
No issues here.

**Comment by Galbi3000** [comment]
> I don't even remember what I contributed xd, but sure thing go ahead.

Same 🙂

**Comment by tom-weiland** [comment]
My contribution was tiny, but this is totally fine by me 😅

**Comment by realDLPS** [comment]
Fine by me :)

**Comment by Clawthorn** [comment]
Much appreciate being asked. Of course I'm okay with this. :)

**Comment by herocrab** [comment]
Agree, ok with me!

**Comment by mafiesto4** [comment]
#91 merged! thanks everyone!
